pytest --alluredir=allure_tdd_reports
pytest --alluredir=allure_tdd_reports test_sendsafely_pytested_blue_top_1.py
pytest --alluredir=allure_tdd_reports test_sendsafely_pytested_bttns_clckd_2.py
pytest --alluredir=allure_tdd_reports test_sendsafely_pytested_sign_up_right_3.py