from selenium.webdriver.common.by import By

# Locators
SND_SFL_PCTR = (By.XPATH, "//img[@src='/img/ss_logo_60_343.png']") # (By.XPATH, "//img[@alt='logo']")
GLB_S_SCHM_PCTR = (By.XPATH, "//img[@src='/img/globe_lines.png']")
E2E_TXT_ECRPTN_TXT = (By.XPATH, "//h1[@class='f_700 f_size_40 l_height50 w_color mb_20 wow fadeInRight']")
ACPT_CCKS_BTN = (By.ID, "cookie_accept")
FTRS_BTN = (By.XPATH, "(//a[@href='/features/'])[1]")  # (By.XPATH, "//a[normalize-space()='Features']")
SLTNS_BTN = (By.XPATH, "//a[@class='dropdown-toggle nav-link']")  # (By.XPATH, "//a[@title='Solutions']")
FV_ELMNTS_DRPDWN_MNU_HR = (By.XPATH, "//li[@class='nav-item']")
SCR_EML_TXT = (By.XPATH, "(//li[@class='nav-item'])[1]")
HLP_DSK_INTGRTN_TXT = (By.XPATH, "(//li[@class='nav-item'])[2]")
SCR_FL_EXCHNG_TXT = (By.XPATH, "(//li[@class='nav-item'])[3]")
SND_SFLY_DRP_ZN_TXT = (By.XPATH, "(//li[@class='nav-item'])[4]")
DVLPR_API_TXT = (By.XPATH, "(//li[@class='nav-item'])[5]")
PRCN_BTN = (By.XPATH, "//a[@href='/pricing/']")  # (By.XPATH, "//a[normalize-space()='Pricing']")
HW_T_WRKS_BTN = (By.XPATH, "//a[@href='/howitworks/']")  # (By.XPATH, "//a[@class='nobr nav-link']")
BLG_BTN = (By.XPATH, "//a[@href='https://blog.sendsafely.com']")  # (By.XPATH, "//a[normalize-space()='Blog']")
LGN_BTN = (By.XPATH, "//a[@class='btn_get btn_hover']")
RQST_DM_BTN = (By.XPATH, "//nobr[normalize-space()='Request Demo']")
SGN_P_BTN = (By.XPATH, "//section[@class='agency_banner_area_two']//a[1]")
LRN_MR_BTN = (By.XPATH, "//a[@id='intro-button']//div[@class='btn btn-lg btn-orange'][normalize-space()='Learn More']")
EML_ADDRSS_FLD = (By.XPATH, "//input[@id='regEmail']")
GT_STRTD_BTN = (By.XPATH, "//button[@id='login-registration-button']")
SCRT_RVW_BTN = (By.XPATH, "//a[normalize-space()='Security Overview']")
SCRT_BG_RPRTNG_FRM_BTN = (By.XPATH, "//a[normalize-space()='Security Bug Reporting Form']")
ENTR_YR_EML_ADDRSS_FLD = (By.XPATH, "//input[@id='email']")
WHT_CTGRY_F_SCRT_BG_FLD = (By.XPATH, "//input[@id='secure_bug_type']")
URL_AFFCTD_FLD = (By.XPATH, "//input[@id='secure_url']")
DSCRPTV_BG_CPTN_FLD = (By.XPATH, "//textarea[@id='secure_caption']")
DSCRPTV_HW_CN_RPLC_FLD = (By.XPATH, "//textarea[@id='secure_poc']")
ADDTNL_INF_MGHT_B_USL_FLD = (By.XPATH, "//textarea[@id='secure_info']")
# DRG_FLS_CLCK_ADD_FL_BTN = (By.ID, "sendsafely-file-input")
# DRG_FLS_CLCK_ADD_FL_BTN = (By.ID, "sendsafely-dropzone")
# DRG_FLS_CLCK_ADD_FL_BTN = (By.ID, "sendsafely-submit")
DRG_FLS_CLCK_ADD_FL_BTN = (By.XPATH, "//input[@data-dropzone='upload-dropzone']")
SBMT_BTN = (By.XPATH, "//button[@id='sendsafely-submit']")