name: BDD Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt webdriver-manager

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install Allure CLI
      run: choco install allurecommandline -y

    - name: Create Allure Reports Directory
      run: mkdir allure_bdd_reports

    - name: Run BDD Tests
      run: python -m behave -f allure_behave.formatter:AllureFormatter -o allure_bdd_reports/ features/

    - name: Generate Allure Report
      run: allure generate allure_bdd_reports --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-bdd
        path: allure-report